language: ruby
rvm:
  - 3.1.3

gemfile:
  - Gemfile
  - Gemfile.next

services:
  - postgresql

before_script:
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:create db:migrate
